INSERT INTO TBL_SELLER (NAME, SALARY, BONUS, GENDER) VALUES ('Michael', 3300, 25, 1);
INSERT INTO TBL_SELLER (NAME, SALARY, BONUS, GENDER) VALUES ('Bruno', 4700, 30, 1);
INSERT INTO TBL_SELLER (NAME, SALARY, BONUS, GENDER) VALUES ('Rogério', 5000, 45, 1);
INSERT INTO TBL_SELLER (NAME, SALARY, BONUS, GENDER) VALUES ('Isabelle', 3400, 40, 2);
INSERT INTO TBL_SELLER (NAME, SALARY, BONUS, GENDER) VALUES ('Elaís', 4700, 50, 2);
INSERT INTO TBL_SELLER (NAME, SALARY, BONUS, GENDER) VALUES ('Jaqueline', 6500, 55, 2);